# 1.  Suppose the manufacturer claims that the mean lifetime of a light bulb is more than 10,000 hours. In a sample of 30 light bulbs, it was found that they only last 9,900 hours on average. Assume the population standard deviation is 120 hours. At .05 significance level, test the claim by the manufacturer?

# Z-Test, Test for Mean, when population S.D. is known. 1 POPn

In [1]:
import scipy.stats as sp
import numpy as np

xbar = 9900

mu_zero = 10000

sigma = 120

n = 30

a = xbar-mu_zero

b = sigma/np.sqrt(n)

z = a/b

print(z)

-4.564354645876384


In [2]:
z_alpha = 1.96

if z<z_alpha:
    print("H0 is rejected.")
else:
    print("H0 is accepted.")

H0 is rejected.


# Z test for mean when Population standard deviation is Unknown. 1 POPn.

In [3]:
#2

import scipy.stats as sp
import numpy as np

xbar = 2.1

mu_zero = 2

sigma = 0.3

n = 51

a = xbar-mu_zero

b = sigma/np.sqrt(n)

z = a/b

print(z)

2.3804761428476193


In [4]:
a = (0.25*(1-0.25))/500
print(a)

0.000375


In [5]:
b = (0.375*(1-0.375))/1000
b

0.000234375

In [6]:
import numpy as np

c = np.sqrt(a+b)
c

0.024685522072664372

In [7]:
d = 0.125/c

print(d)

5.063696835418333


# Standard Deviation Formula

In [ ]:
mean = 

n = 

sd = (mean*(mean-1))/n)

print(sd) #Standard deviation

# P cap formula

In [ ]:
proportion = 

n = 

pcap = proportion/n

print(pcap)

# STANDARD SCORE FORMULA

In [1]:
# stats.zscore() method 

import numpy as np 
from scipy import stats 
    
arr1 = [[20, 2, 7, 1, 34], 
        [50, 12, 12, 34, 4]] 
  
arr2 = [[50, 12, 12, 34, 4],  
        [12, 11, 10, 34, 21]] 
  
print ("\narr1 : ", arr1) 
print ("\narr2 : ", arr2) 
  
print ("\nZ-score for arr1 : \n", stats.zscore(arr1)) 
print ("\nZ-score for arr1 : \n", stats.zscore(arr1, axis = 1))


arr1 :  [[20, 2, 7, 1, 34], [50, 12, 12, 34, 4]]

arr2 :  [[50, 12, 12, 34, 4], [12, 11, 10, 34, 21]]

Z-score for arr1 : 
 [[-1. -1. -1. -1.  1.]
 [ 1.  1.  1.  1. -1.]]

Z-score for arr1 : 
 [[ 0.57251144 -0.85876716 -0.46118977 -0.93828264  1.68572813]
 [ 1.62005758 -0.61045648 -0.61045648  0.68089376 -1.08003838]]


In [2]:
import numpy as np 
from scipy import stats 
   
arr2 = [[50, 12, 12, 34, 4],  
        [12, 11, 10, 34, 21]] 
  
print ("\nZ-score for arr2 : \n", stats.zscore(arr2, axis = 0)) 
print ("\nZ-score for arr2 : \n", stats.zscore(arr2, axis = 1)) 


Z-score for arr2 : 
 [[ 1.  1.  1. nan -1.]
 [-1. -1. -1. nan  1.]]

Z-score for arr2 : 
 [[ 1.62005758 -0.61045648 -0.61045648  0.68089376 -1.08003838]
 [-0.61601725 -0.72602033 -0.83602341  1.80405051  0.37401047]]


C:\Users\Abhijit Chendvankar\Anaconda3\lib\site-packages\scipy\stats\stats.py:2419: RuntimeWarning: invalid value encountered in true_divide
  return (a - mns) / sstd


# Test for Equality of Means when S.D. is known 2 POPULATIONS

In [ ]:
x1 = 74
x2 = 78
n1 = 40
n2 = 50
sd1 = 8     #when only one standard deviation is known assume its value for both populations
sd2 = 7

z = (x2-x1)/(np.sqrt((sd1*sd1/n1)+(sd2*sd2/n2)))
print(z)

In [ ]:
#6

x1 = 74
x2 = 75
n1 = 40
n2 = 50
sd = 7

z = (x2-x1)/(np.sqrt((sd*sd/n1)+(sd*sd/n2)))
print(z)

In [ ]:
#7

x1 = 74
x2 = 75
n1 = 40
n2 = 50
sd = 7

z = (x2-x1)/(np.sqrt((sd*sd/n1)+(sd*sd/n2)))
print(z)

In [ ]:
import scipy.stats as sp

sp.norm.ppf(0.025)

In [ ]:
sp.norm.ppf(0.95)

In [9]:
#

x1 = 74
x2 = 78
n1 = 40
n2 = 50
sd1 = 8
sd2 = 7

z = (x2-x1)/(np.sqrt((sd1*sd1/n1)+(sd2*sd2/n2)))
print(z)

2.4902912254587615


In [10]:
np.std(46,ddof=1)

C:\Users\Abhijit Chendvankar\Anaconda3\lib\site-packages\numpy\core\_methods.py:140: RuntimeWarning: Degrees of freedom <= 0 for slice
  keepdims=keepdims)
C:\Users\Abhijit Chendvankar\Anaconda3\lib\site-packages\numpy\core\_methods.py:132: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)


nan

In [6]:
#sample question paper

#1

import numpy as np
import scipy.stats as sp

#

x1 = 20.14458
x2 = 30.48101
n1 = 249
n2 = 79
sd1 = 6.41470     #when only one standard deviation is known assume its value for both populations
sd2 = 6.1071

z = (x2-x1)/(np.sqrt((sd1*sd1/n1)+(sd2*sd2/n2)))
print(z)

12.947225421738217


In [3]:
#2

ex = [1, 3, 6, 0, 1, 1, 2, 1, 4]

np.mean(ex)

2.111111111111111

In [4]:
np.std(ex,ddof=1)

1.90029237516523

In [7]:
sp.norm.interval(0.05,2.111111111111111,1.90029237516523)

(1.9919498991144426, 2.2302723231077795)