# 1.  A large group of students took a test in Physics and the final grades have a mean of 71.78 and a standard deviation of 11.11. If we can approximate the distribution of these grades by a normal distribution, what percent of the students

a. scored higher than 85?
b. should pass the test (grades≥60)?
c. should fail the test (grades<60)?

In [11]:
import scipy.stats as sp
import numpy as np
import seaborn as sns

#mean = 71.78

#sd = 11.11



In [5]:
#a. scored higher than 85

1-sp.norm.cdf(85,71.78,11.11)

0.11703911654282828

In [6]:
#b. should pass the test (grades≥60)

1-sp.norm.cdf(60,71.78,11.11)

0.8554973017141121

In [7]:
#c. should fail the test (grades<60)

sp.norm.cdf(60,71.78,11.11)

0.14450269828588796

# 2.  A study was conducted to find average starting salary of recent high school graduates who started full-time jobs instead of college study. A random sample of size 91 gave a sample mean salary of Rs. 22,500 with a standard deviation of Rs. 2409. Find a 95% confidence interval for average starting income.

In [10]:
#n = 91

#mean = 22500

#sd = 2409

sp.norm.interval(0.95,22500,2409/np.sqrt(91))

(22005.04673340358, 22994.95326659642)

# 3.  Follow the instructions given below; (Use Python Programming)
[5 Marks]
a. Generate 3000 random numbers from Normal distribution with mean 168.5 and standard deviation 12.4. (say A)
1
b. Generate 3000 random numbers from Normal distribution with mean 112.8 and standard deviation 14.3. (Say B)
1
c. Add A and B data points (say C=A+B). Use suitable method/test to verify, if the new variable (C) follows Normal distribution. Justify your answer.

In [13]:
a = np.random.normal(168.5,12.4,3000)

a

array([167.72944182, 171.10191691, 163.05962587, ..., 194.74766125,
       167.30028332, 148.8279448 ])

In [14]:
b = np.random.normal(112.8,14.3,3000)
b

array([145.83209367, 113.79706698,  86.79936717, ..., 122.06439252,
        96.32661843,  80.37602001])

In [16]:
c = np.array(a) + np.array(b)

c

array([313.5615355 , 284.89898388, 249.85899304, ..., 316.81205377,
       263.62690175, 229.2039648 ])

In [18]:
sw = sp.shapiro(c)
sw

(0.9994869232177734, 0.6304984092712402)

# 4. It is known that on a certain highway there are on the average 2 accidents per day.
[5 Marks]
a. Find the probability that in a given week there will be less than 3 accidents.
2.5
b. Find the probability that in a given week there will be greater than 3 and less than 7 accidents.

In [23]:
#a

sp.poisson.cdf(2,14)

9.396274525870306e-05

In [25]:
#b

sp.poisson.cdf(6,14)-sp.poisson.cdf(2,14)

0.014133955599002814

# 5.  It is claimed that a random sample of 200 tyres with a mean life of 12450 kms is drawn from a population of tyres which has a mean life of 14200 kms and a standard deviation of 1248 kms. Test the validity of claim at 5% level of significance.

In [26]:
sp.norm.ppf(0.025)

-1.9599639845400545

In [27]:
sp.norm.ppf(0.975)

1.959963984540054

In [29]:
import scipy.stats as sp
import numpy as np

xbar = 12450

mu_zero = 14200

sigma = 1248

n = 200

a = xbar-mu_zero

b = sigma/np.sqrt(n)

z = a/b

print(z)

-19.83071902366119


In [30]:
z_alpha = 1.96

if z<z_alpha:
    print("H0 is rejected.")
else:
    print("H0 is accepted.")

H0 is rejected.


# 6.  Experiments have been established to test electric bulbs. The life of bulbs is found normally distributed with mean 13279 hrs. and standard deviation 1256 hrs. A bulb manufacturing company decides to replace fused (failed) bulbs free of cost which fails to meet a certain minimum life then, what should be the minimum life of bulb, company must guarantee if the company can afford to replace only half percent of the bulbs sold.

In [31]:
sp.norm.ppf(0.005,13279,1256)

10043.758394742581

# 7.  The sales data related to an ice-cream brand before and after a campaign are as follows:
[5 Marks]

Shops: a b c d e f
Before Campaign: 530 280 310 480 500 420
After Campaign: 580 290 300 550 560 450
Is campaign successful? Test at 5% level of significance.

In [33]:
before = [530,280,310,480,500,420]
after = [580,290,300,550,560,450]

sp.ttest_rel(before,after) #paired T-test formula

Ttest_relResult(statistic=-2.7815179498365916, pvalue=0.0388322974181411)

# 8.  Among a group of people from small town, 45% are drinkers and remaining are non-drinkers. The probability of a drinker dying in a given month is 0.04 while the probability for a non-drinker is 0.01. Given that, in a month one person dies, what is the probability that he is a drinkers.

In [ ]:
p = 0.45*0.04/(0.45*0.04)+(0.55*0.01)

# 9.  Wankhede Stadium has 6 light towers with 25 high-intensity flood lights mounted on each. Sometimes an entire light tower will go dark. Mr. Gupta, Head of maintenance, wonder what the distribution of light tower failure is! He knows that any individual tower has a probability of 0.05 of failure during cricket game and that the towers fail independently. In order to play game at least 3 towers should be working. What is the probability that randomly selected game calls off because of floodlight issue?

In [36]:
1-sp.binom.cdf(2,6,0.05)

0.0022298437500000157